1.留言；
2.历史任务参照；
3.搜索范围应包括历史任务；done
4.已完成的任务自动导入到历史任务中；
5.搜索到任务后点击人名能查看人物基本信息；
6.修复新建任务时不添加文件也可正常保存；
7.新建任务和执行任务时上传的文件可以多余一个；



ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right
 syntax to use near '\\u90dd\\u9e3f\\u5ef6', u'\\u674e\\u676d']' and mission_id = '56'' at line 1")  
 //任务完成提交的role={{mission_doer}}
 
 
 
 Traceback (most recent call last):
  File "F:\Python27\lib\site-packages\web\application.py", line 239, in process
    return self.handle()
  File "F:\Python27\lib\site-packages\web\application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "F:\Python27\lib\site-packages\web\application.py", line 462, in _delegate
    return handle_class(cls)
  File "F:\Python27\lib\site-packages\web\application.py", line 438, in handle_class
    return tocall(*args)
  File "index.py", line 493, in GET
    message_list = message_list)
  File "index.py", line 109, in render_template
    return jinja_env.get_template(template_name).render(context)
  File "F:\Python27\lib\site-packages\jinja2\environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "F:\Python27\lib\site-packages\jinja2\environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "templates/user\view_mission_publisher_j.html", line 1, in top-level template code
    <h2 class="contentTitle">{{mission_view[0]['mission_status']}}</h2>
  File "F:\Python27\lib\site-packages\jinja2\environment.py", line 378, in getitem
    return obj[argument]
UndefinedError: tuple object has no element 0
//已建任务未通过详情出错



mission_id,mission_status  :
56
已完成
127.0.0.1:62230 - - [22/Jul/2015 20:05:52] "HTTP/1.1 GET /change_mission_sta/" - 200 OK
127.0.0.1:62230 - - [22/Jul/2015 20:05:55] "HTTP/1.1 GET /mission_state/" - 200 OK
Traceback (most recent call last):
  File "F:\Python27\lib\site-packages\web\application.py", line 239, in process
    return self.handle()
  File "F:\Python27\lib\site-packages\web\application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "F:\Python27\lib\site-packages\web\application.py", line 462, in _delegate
    return handle_class(cls)
  File "F:\Python27\lib\site-packages\web\application.py", line 438, in handle_class
    return tocall(*args)
  File "index.py", line 483, in GET
    m = mission.mission_view_status(mission_doer,role,mission_id,mission_status)
  File "F:\Python27\code\TDOA\mission.py", line 224, in mission_view_status
    cursor.execute("select mission_doer from missions_doers where mission_id = %s ;"%(m_list_user[0]['mission_id']))
IndexError: tuple index out of range

//已建任务动态已完成详情出错



王松
file_list(file_type, mission_id, role)   :
()
//我的任务动态未通过初试任务附件没有了

bug原因： file.py file_type_change 逻辑问题；修改之前还要判断mission_doer,初始参考type始终不变，


